version: '3.8'
services:
  dao_bot:
    container_name: dao_bot
    build: .
    command: npm run dev
    ports:
      - "8080:8080" # Убедитесь, что порт соответствует тому, который используется вашим ботом
    restart: on-failure
    environment:
      - MODE=${MODE}
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - dao_db

  dao_db:
    container_name: dao_db
    image: postgres:13
    restart: on-failure
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - dao_db_data:/var/lib/postgresql/data

volumes:
  dao_db_data:

networks:
  default:
